// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Collepse: typeof import('./src/components/Collepse.vue')['default']
    'Collepse的副本': typeof import('./src/components/Collepse的副本.vue')['default']
    CollepseItem: typeof import('./src/components/CollepseItem.vue')['default']
    'CollepseItem的副本': typeof import('./src/components/CollepseItem的副本.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'HelloWorld的副本': typeof import('./src/components/HelloWorld的副本.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
